version: '3'
services:
  app:
    container_name: ${ENV}_app
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api/:/usr/app
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
  # front:
  #   container_name: ${ENV}_front
  #   build:
  #     context: ./front
  #     dockerfile: ./front/Dockerfile
  #   tty: true
  #   ports:
  #    - 8080:8080
  # db:
  #   container_name: ${ENV}_db
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   command: -c 'config_file=/etc/postgresql/postgresql.conf'
  #   volumes:
  #     - ./db/postgresql.conf:/etc/postgresql/postgresql.conf
  #     - ./db/data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #     LANGUAGE: "ja_JP.UTF-8"
  #     LANG: "ja_JP.UTF-8"
  #     LC_ALL: "ja_JP.UTF-8"
  #     TZ: "Asia/Tokyo"
